### ISSUE TITLE
[!] Please check that the Metasploit framework modules path is properly defined in line 18 of this script

### ISSUE THREAD

**Issue by omarsalloum** [milo2012/metasploitHelper#11]
**# How i fix this problem** 

[!] Please check that the Metasploit framework modules path is properly defined in line 18 of this script

My O.S Kali Linux 2 
uname -a :  4.3.0-kali1-amd64 #1 SMP Debian 4.3.3-5kali4 (2016-01-13) x86_64 GNU/Linux

**Comment by pieterhouwen** [comment]
^see above, same problem.

4.8.0-kali2-amd64 SMP Debian 4.8.15-1kali 2016-12-23) x86_64

**Comment by milo2012** [comment]
Please make sure that metasploit is installed in
/pentest/metasploit-framework folder.
If not, please update line 18 in metasploitHelper.py to reflect the updated
path.

Line 18 in metasploitHelper.py
path = "/pentest/metasploit-framework/modules/"

If you do not have Metasploit installed, please follow the below steps (if
you are using debian or kali linux) and then run metasploitHelper again.

$ cd /pentest
$ apt-get install git-core -y
$ git clone https://github.com/rapid7/metasploit-framework

**Comment by pieterhouwen** [comment]
metasploit-framework is located at /usr/share/metasploit-framework on out-of-the-box Kali installations as far as I know, but indeed, I pointed it to the right location and it worked!

**Comment by milo2012** [comment]
@pieterhouwen   iThanks for the update as it might be useful to others facing the same issue.
