### ISSUE TITLE
msfHelper -u errors

### ISSUE THREAD

**Issue by pieterhouwen** [milo2012/metasploitHelper#19]
while using the -u option I get greeted by the following error

/usr/share/metasploit-framework/msfupdate:275:in `update_apt!': undefined method `blank?' for nil:NilClass (NoMethodError)
	from /usr/share/metasploit-framework/msfupdate:140:in `block in run!'
	from /usr/share/metasploit-framework/msfupdate:134:in `chdir'
	from /usr/share/metasploit-framework/msfupdate:134:in `run!'
	from /usr/share/metasploit-framework/msfupdate:326:in `<main>'

**Comment by milo2012** [comment]
If you run the command msfupdate directly, did you get any errors ?

-- 
Keith

**Comment by pieterhouwen** [comment]
Some of the update features were succesful, I've added the output below:

root@supersecretkali:~/metasploitHelper# python msfHelper.py -u
[*] Launching Metasploit msfrpcd
[*] MSGRPC starting on 127.0.0.1:55552 (NO SSL):Msg...
[*] URI: /api/
[*] MSGRPC backgrounding at 2017-05-30 07:24:54 -0400...
[*] Running msfupdate
[*]
[*] Attempting to update the Metasploit Framework...
[*]

[*] Checking for updates via the APT repository
[*] Note: expect weekly(ish) updates using this method
/usr/share/metasploit-framework/msfupdate:275:in `update_apt!': undefined method `blank?' for nil:NilClass (NoMethodError)
	from /usr/share/metasploit-framework/msfupdate:140:in `block in run!'
	from /usr/share/metasploit-framework/msfupdate:134:in `chdir'
	from /usr/share/metasploit-framework/msfupdate:134:in `run!'
	from /usr/share/metasploit-framework/msfupdate:326:in `<main>'

[*] Loaded 2602 modules from Metasploit
[*] Updating msfHelper.db
[!] Encountered Error: Retrying in 5 seconds

[*] Adding: scanner/varnish/varnish_cli_login
[*] Adding: scanner/snmp/cambium_snmp_loot
[*] Adding: scanner/smb/smb_ms17_010
[*] Adding: scanner/scada/moxa_discover
[*] Adding: scanner/http/dnalims_file_retrieve
[*] Adding: scanner/http/gavazzi_em_login_loot
[*] Adding: scanner/http/epmp1000_cmd_exec
[*] Adding: scanner/http/epmp1000_dump_hashes
[*] Adding: scanner/http/epmp1000_web_login
[*] Adding: scanner/http/intel_amt_digest_bypass
[*] Adding: scanner/http/epmp1000_dump_config
[*] Adding: multi/http/trendmicro_threat_discovery_admin_sys_time_cmdi
[*] Adding: multi/http/mediawiki_syntaxhighlight
[*] Adding: multi/http/builderengine_upload_exec
[*] Adding: windows/iis/iis_webdav_scstoragepathfromurl
[*] Adding: windows/smb/ms17_010_eternalblue
[*] Adding: windows/http/serviio_checkstreamurl_cmd_exec
[*] Adding: linux/ssh/mercurial_ssh_exec
[*] Adding: linux/ssh/solarwinds_lem_exec
[*] Adding: linux/http/crypttech_cryptolog_login_exec
[*] Adding: linux/http/github_enterprise_secret
[*] Adding: linux/http/huawei_hg532n_cmdinject
[*] Adding: linux/http/netgear_wnr2000_rce
[*] Adding: linux/http/wipg1000_cmd_injection
[*] Adding: linux/http/dnalims_admin_exec
[*] Adding: linux/http/logsign_exec
[*] Adding: unix/webapp/wp_phpmailer_host_header
[!] Please set a target
root@supersecretkali:~/metasploitHelper# msfupdate
[*]
[*] Attempting to update the Metasploit Framework...
[*]

[*] Checking for updates via the APT repository
[*] Note: expect weekly(ish) updates using this method
/usr/bin/msfupdate:275:in `update_apt!': undefined method `blank?' for nil:NilClass (NoMethodError)
	from /usr/bin/msfupdate:140:in `block in run!'
	from /usr/bin/msfupdate:134:in `chdir'
	from /usr/bin/msfupdate:134:in `run!'
	from /usr/bin/msfupdate:326:in `<main>'
root@supersecretkali:~/metasploitHelper#

**Comment by milo2012** [comment]
There appears to be something wrong with the msfupdate.  Did you managed to try it with a fresh installation of Kali linux?

**Comment by pieterhouwen** [comment]
I had a clean Kali, cloned the git, installed it and ran the update. That seemed to work.

I'm now updating the Kali to the latest version and then trying again, but I think I won't be seeing the error anymore.

**Comment by milo2012** [comment]
Glad to know and thanks for your help. Please feel free to raise a new issue if you have any suggestions or face any issues in future .
