### ISSUE TITLE
multiple ips

### ISSUE THREAD

**Issue by NoorQureshi** [milo2012/metasploitHelper#21]
is there anyway to scan multiple IP Addresses?

**Comment by milo2012** [comment]
There are a few ways to do so
Below is the command to scan an IP
$ python msfHelper.py 192.168.1.6 -i

You can scan a subnet by running
$ python msfHelper.py 192.168.1.0/24 -i

Or scan a file containing list of IP addresses
$ python msfHelper.py ips.txt -i

Let me know if you face any issues


-- 
Keith
