### ISSUE TITLE
python msfHelper.py -i /root/Desktop/tt.xml

### ISSUE THREAD

**Issue by saado05** [milo2012/metasploitHelper#22]
[*] Launching Metasploit msfrpcd
[*] MSGRPC starting on 127.0.0.1:55552 (NO SSL):Msg...
[*] URI: /api/
[*] MSGRPC backgrounding at 2017-06-30 06:17:02 -0400...
[*] Reading from msfHelper.db
Traceback (most recent call last):
  File "msfHelper.py", line 2111, in <module>
    portsList,httpsList,httpList,osList=parseNmap(target)
  File "msfHelper.py", line 176, in parseNmap
    rep = NmapParser.parse_fromfile(filename)
NameError: global name 'NmapParser' is not defined

**Comment by milo2012** [comment]
Did you managed to install the dependencies ?

$ apt-get install git-core -y

$ git clone https://github.com/SpiderLabs/msfrpc

$ cd msfrpc && python setup.py install

$ pip install tabulate termcolor python-libnmap msgpack-python
tabulate beautifulsoup4 termcolor requests

**Comment by saado05** [comment]
yes i installed all of the requirements

**Comment by milo2012** [comment]
Are you able to run the below commands
Run "python" followed by "from libnmap.parser import NmapParser" without
the quotes.

Let me know if you get an error message.
If so, it means that the libnmap library is not installed properly
-- 
Keith

**Comment by saado05** [comment]
yes its runing normal 
i try this command but same probleme 
python msfHelper.py -i 192.168.1.1
[*] Reading from msfHelper.db
Traceback (most recent call last):
  File "msfHelper.py", line 2141, in <module>
    nmapFilename=runNmap(target)
  File "msfHelper.py", line 1941, in runNmap
    print setColor('[*] Running Nmap against target: '+targetIP, bold, color="red")
  File "msfHelper.py", line 278, in setColor
    retVal = colored(message, color=color, on_color=onColor, attrs=("bold",))
NameError: global name 'colored' is not defined
......................
there are many problems 
i think from msfhelper.db

**Comment by milo2012** [comment]
Please provide me the output of the command I asked earlier. Thank you

I have just tried running msfHelper yesterday.

**Comment by saado05** [comment]
# python
Python 2.7.13 (default, Jan 19 2017, 14:48:08) 
[GCC 6.3.0 20170118] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> from libnmap.parser import NmapParser
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named libnmap.parser

**Comment by milo2012** [comment]
The error message shows that the libnmap Python library is not installed
properly.
Can you reinstall the dependencies again

**Comment by saado05** [comment]
the same probleme

**Comment by milo2012** [comment]
If you still having issues, please try the docker image as all the dependencies are installed and works.
Please open another ticket if you still face any issues.

$ docker pull milo2012/metasploithelper
$ docker run --rm -it milo2012/metasploithelper
$ python msfHelper.py -a testphp.vulnweb.com
