### ISSUE TITLE
Double requirement given: tabulate (already in tabulate, name='tabulate')

### ISSUE THREAD

**Issue by arkxdns** [milo2012/metasploitHelper#24]
Hello,

I do not know much about python, can you help me for this ?

pip install tabulate termcolor python-libnmap msgpack-python tabulate beautifulsoup4 termcolor requests

I,v got this install error message : 

/usr/bin/pip run on Mon Apr  2 11:23:17 2018
Double requirement given: tabulate (already in tabulate, name='tabulate')
Exception information:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/pip/basecommand.py", line 122, in main
    status = self.run(options, args)
  File "/usr/lib/python2.7/dist-packages/pip/commands/install.py", line 257, in run
    InstallRequirement.from_line(name, None))
  File "/usr/lib/python2.7/dist-packages/pip/req.py", line 989, in add_requirement
    % (install_req, self.get_requirement(name), name))
InstallationError: Double requirement given: tabulate (already in tabulate, name='tabulate')

Thanks !

**Comment by milo2012** [comment]
I have updated the README.md.  Thanks for your report.
The command has been updated to 
$ pip install tabulate termcolor python-libnmap msgpack-python beautifulsoup4 termcolor requests
