### ISSUE TITLE
Please mention coding standards

### ISSUE THREAD

**Issue by surajssd** [milo2012/metasploitHelper#5]
Hi,

I would like to help in this project. Please mention what coding standards have you used? Please use default coding standards like 4 spaces for tab and all.

**Comment by milo2012** [comment]
Please feel free to suggest any new features which you would like to see in this script.

**Comment by surajssd** [comment]
A simple one liner on the code could replace all tabs with 4 spaces. 4 spaces is a coding standard in all the python programs. 

new_file = open("changed_file', 'w')
lines = [line.replace('\\t', "    ") for line in open("metasploitHelper.py").read().split("\n")]
changed_text

**Comment by milo2012** [comment]
Thank you for reporting this. The changes have been made with some slight adjustments. 
https://raw.githubusercontent.com/milo2012/metasploitHelper/master/metasploitHelper.py
