### ISSUE TITLE
Cannot able to load..

### ISSUE THREAD

**Issue by g33xter** [milo2012/metasploitHelper#7]
![screenshot from 2015-03-29 23 37 30](https://cloud.githubusercontent.com/assets/8503135/6891190/a24346dc-d66c-11e4-9c83-7396a646d9b4.png)

**Comment by milo2012** [comment]
Hi,
May I know which version of Python are you using ?
Are you using Python2.7 ? Thanks

**Comment by milo2012** [comment]
Hi, this issue has been resolved with the latest commit, I have added '#!/usr/bin/env python' to the first line.
Btw, this github repo is for metasploitHelper and not nmap2nessus.  I think you have posted in the wrong Github page.  I will be closing this issue. Let me know if you still face any issues.

**Comment by g33xter** [comment]
That issue resolved, but facing another one. 
![screenshot from 2015-03-30 03 46 12](https://cloud.githubusercontent.com/assets/8503135/6894929/66610460-d68f-11e4-8977-9876a314f578.png)

**Comment by milo2012** [comment]
pip install requests --upgrade 
Please run this to upgrade the requests Python module 

I will update the README

**Comment by g33xter** [comment]
Thanks a lot, it worked like charm!!

**Comment by g33xter** [comment]
Facing two different errors in different situations. The 1st error is without logging into nessus from browser & 2nd is logging into nessus from browser.
![screenshot from 2015-03-30 04 09 36](https://cloud.githubusercontent.com/assets/8503135/6895219/aaf7b09e-d692-11e4-9c3d-359f022a723d.png)

**Comment by milo2012** [comment]
May I ask if you are using the latest version of Nessus 6.3.X ? I will add debug code later today so that we can see what went wrong.

**Comment by milo2012** [comment]
Thank you for your patience while we find out what happened on your end

**Comment by g33xter** [comment]
Nessus version really matters??

**Comment by milo2012** [comment]
There is a difference in the nessus api between Nessus 5 and 6. One is REST interface and the other I cannot recall at the moment 
I tested it on Nessus 6.3.2 to be exact.
Could you let me know if you are using Nessus 6 ? It might not be this issue but I just wanted to be sure. Thanks

**Comment by g33xter** [comment]
In kali linux it is version 5 & in Ubuntu it's 6

**Comment by milo2012** [comment]
Sorry I am confused. Do you mean that you have tested it on both Nessus 5 and 6.  Did you get the same error on Nessus 6?

**Comment by g33xter** [comment]
Sorry for the delay in replying. Its working fine. Thanks a lot.

P.S: Impressive Program.

**Comment by milo2012** [comment]
Thanks !!!
